### Request access token from auth server
POST http://localhost:8080/oauth2/token
Authorization: Basic YmFja2VuZC1jbGllbnQ6cGFzc3dvcmQ=
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials&scope=read write

### Request Dad Joke
GET http://localhost:8081/api/dadjoke
Authorization: Bearer eyJraWQiOiIwODU5OGVkOC1mZTc4LTQ3ZDMtYTIyOS00MGI0ZTlkYjA5NTkiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJiYWNrZW5kLWNsaWVudCIsImF1ZCI6ImJhY2tlbmQtY2xpZW50IiwibmJmIjoxNzI3OTEwNTc2LCJzY29wZSI6WyJyZWFkIiwid3JpdGUiXSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwIiwiZXhwIjoxNzI3OTEwODc2LCJpYXQiOjE3Mjc5MTA1NzYsImp0aSI6ImQyM2Y2ZmIyLTkwMWItNGNkNC1iZDAxLTBmNDNjMmQxZTEzZSJ9.sM38Thc3-uz8OwW1bOE24RiggDCAfN6NxJJ8ksS8t5zxEx76rSWc5_GiG-dnv42vTuROyODy4PIv-uhBxcV07ElLII6DZ75PtL7MaVKBMgoXl43FUFs8d70bQNUqIoc09lSUeYdyRQFHNfRhySPDWPLwOZzJMulJ98l8Q2PIRgb-K8wlnN94--SKxJxDcU8GU-RE5r55PpQSrRIIWAoyt83iGfd0mlD4SOWpH4J8ItR9-pDmevGQQdTQPTJQbpIkzRZnBpMs80phMl0McuAadRR_HAZq51q66KQ9U8TlHtwjcjyH1lBuCtxEvn10qIcTZOmuTZ_3uTcr3UbRMmU0dQ

