### login request
POST http://localhost:8080/login
Content-Type: application/x-www-form-urlencoded

username=admin&password=password

### Request access token for backend client
POST http://localhost:8080/oauth2/token
Authorization: Basic YmFja2VuZC1jbGllbnQ6cGFzc3dvcmQ=
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials&scope=read write