### Request access token from auth server
POST http://localhost:8080/oauth2/token
Authorization: Basic YmFja2VuZC1jbGllbnQ6cGFzc3dvcmQ=
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials&scope=read write

### Request Dad Joke
GET http://localhost:8081/api/v1/dadjoke
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IkdwT3RCbzRDcjRTd3ZGOVA0ZWZMOCJ9.eyJpc3MiOiJodHRwczovL2Rldi10amRxNGF2dzB4Y21zN25pLnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJYMGdEcVZHcm9zZ1VmTkJoeTdUT3pGNmlNS1VNbEtuSkBjbGllbnRzIiwiYXVkIjoiaHR0cDovL3dpc2VjcmFjay5kbW9oaW5kcnUuZGV2IiwiaWF0IjoxNzI5NjY5NDE0LCJleHAiOjE3Mjk3NTU4MTQsImd0eSI6ImNsaWVudC1jcmVkZW50aWFscyIsImF6cCI6IlgwZ0RxVkdyb3NnVWZOQmh5N1RPekY2aU1LVU1sS25KIn0.r-3AsTPQfF-E9shnmz7NNZT3WFrehVtH9o9DMLPZD9H1d_f_hv9AeI8-RCwElQCWEalYpizA-wooWLUZWIHIi1ukp5wGERs43Al96PGBIWHr7uHyqMRL0-BBBzCkR4YGlelxUn0Klyi8hiBbxR0wR7OolVrWSPFlU7cdeE7Ly75cbUdcz_L5yje5KzprF0hFZy7k6_XAsRL6aTXmn7JaPgu_n_47Fz2nsiI-JDL6HxeMsWH65vVc6SpHuD7sOBNFO45bIe9G0kOG4OAZ3c2ZXAb3kqa14QyDbbXWvejWloONjDVSKQMcliLViK1rq3cV5KGp7Ju67VQ_Z0ffXQZt7Q

### Request Quote of the day
GET http://localhost:8081/api/v1/quote
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IkdwT3RCbzRDcjRTd3ZGOVA0ZWZMOCJ9.eyJpc3MiOiJodHRwczovL2Rldi10amRxNGF2dzB4Y21zN25pLnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJYMGdEcVZHcm9zZ1VmTkJoeTdUT3pGNmlNS1VNbEtuSkBjbGllbnRzIiwiYXVkIjoiaHR0cDovL3dpc2VjcmFjay5kbW9oaW5kcnUuZGV2IiwiaWF0IjoxNzI5NjY5NDE0LCJleHAiOjE3Mjk3NTU4MTQsImd0eSI6ImNsaWVudC1jcmVkZW50aWFscyIsImF6cCI6IlgwZ0RxVkdyb3NnVWZOQmh5N1RPekY2aU1LVU1sS25KIn0.r-3AsTPQfF-E9shnmz7NNZT3WFrehVtH9o9DMLPZD9H1d_f_hv9AeI8-RCwElQCWEalYpizA-wooWLUZWIHIi1ukp5wGERs43Al96PGBIWHr7uHyqMRL0-BBBzCkR4YGlelxUn0Klyi8hiBbxR0wR7OolVrWSPFlU7cdeE7Ly75cbUdcz_L5yje5KzprF0hFZy7k6_XAsRL6aTXmn7JaPgu_n_47Fz2nsiI-JDL6HxeMsWH65vVc6SpHuD7sOBNFO45bIe9G0kOG4OAZ3c2ZXAb3kqa14QyDbbXWvejWloONjDVSKQMcliLViK1rq3cV5KGp7Ju67VQ_Z0ffXQZt7Q