### Request access token from auth server
POST http://localhost:8080/oauth2/token
Authorization: Basic YmFja2VuZC1jbGllbnQ6cGFzc3dvcmQ=
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials&scope=read write

### Request Dad Joke
GET http://localhost:8081/api/v1/dadjoke
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IkdwT3RCbzRDcjRTd3ZGOVA0ZWZMOCJ9.eyJpc3MiOiJodHRwczovL2Rldi10amRxNGF2dzB4Y21zN25pLnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJnb29nbGUtb2F1dGgyfDExNzI1OTU5MTIwODM4NTMyNzYyNiIsImF1ZCI6WyJodHRwczovL2Rldi10amRxNGF2dzB4Y21zN25pLnVzLmF1dGgwLmNvbS9hcGkvdjIvIiwiaHR0cHM6Ly9kZXYtdGpkcTRhdncweGNtczduaS51cy5hdXRoMC5jb20vdXNlcmluZm8iXSwiaWF0IjoxNzI5NDI1NzIzLCJleHAiOjE3Mjk1MTIxMjMsInNjb3BlIjoib3BlbmlkIiwiYXpwIjoiT1I2bzAxSG5DbTRsNnViZ2I1aEtJMXNsRGJQQ3FLREsifQ.ZQbRVfJs1VB0hoqKuGLJ1gatJiYSczObL0JrdGSyrdsOeiclzU0zfAJzhIhqFio8qJRmJDakicSHsAU5IwExI0-UsAJExxTLumG_3toYcwvdSKxwxBOOwD4Ek7KPxG7rCajqNfl1XjqLUPMr7IOwjFZ21JPsH2vNajIwUEZQcQQQOK_h0vdedZti9uLvJmuLOliNC9488Ynw528Mk4RUe1bBslbCYzjwaP4cjK9T3-K7nc5evkllOSKn3hWmXgjB0AGVdNQHx_J1bGMCdJk4UfY-mri85nKHwIPr3tR1-giDVFNw61QP1B9-X9DayMh9FesyawFL9CGbuAI3ik6HHw

### Request Quote of the day
GET http://localhost:8081/api/v1/quote
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IkdwT3RCbzRDcjRTd3ZGOVA0ZWZMOCJ9.eyJpc3MiOiJodHRwczovL2Rldi10amRxNGF2dzB4Y21zN25pLnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJnb29nbGUtb2F1dGgyfDExNzI1OTU5MTIwODM4NTMyNzYyNiIsImF1ZCI6WyJodHRwczovL2Rldi10amRxNGF2dzB4Y21zN25pLnVzLmF1dGgwLmNvbS9hcGkvdjIvIiwiaHR0cHM6Ly9kZXYtdGpkcTRhdncweGNtczduaS51cy5hdXRoMC5jb20vdXNlcmluZm8iXSwiaWF0IjoxNzI5NDI1NzIzLCJleHAiOjE3Mjk1MTIxMjMsInNjb3BlIjoib3BlbmlkIiwiYXpwIjoiT1I2bzAxSG5DbTRsNnViZ2I1aEtJMXNsRGJQQ3FLREsifQ.ZQbRVfJs1VB0hoqKuGLJ1gatJiYSczObL0JrdGSyrdsOeiclzU0zfAJzhIhqFio8qJRmJDakicSHsAU5IwExI0-UsAJExxTLumG_3toYcwvdSKxwxBOOwD4Ek7KPxG7rCajqNfl1XjqLUPMr7IOwjFZ21JPsH2vNajIwUEZQcQQQOK_h0vdedZti9uLvJmuLOliNC9488Ynw528Mk4RUe1bBslbCYzjwaP4cjK9T3-K7nc5evkllOSKn3hWmXgjB0AGVdNQHx_J1bGMCdJk4UfY-mri85nKHwIPr3tR1-giDVFNw61QP1B9-X9DayMh9FesyawFL9CGbuAI3ik6HHw